plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nksports.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nksports.app'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'com.onesignal:OneSignal:5.1.21'
}
